"""CashClose deterministic finance engine.

The public surface is deliberately dependency-light so FastAPI tools, workers,
and tests can all call the same audited calculations.
"""

from .allocation_solver import (
    Allocation,
    AllocationCandidate,
    AllocationSolution,
    AllocationStatus,
    GlobalAllocation,
    GlobalAllocationSolution,
    GlobalAllocationStatus,
    solve_global_allocation,
    solve_payment_allocation,
    verify_allocation,
)
from .candidate_generation import (
    CandidatePolicy,
    InvoiceRecord,
    MatchCandidate,
    TransactionRecord,
    find_candidate_invoices,
    generate_candidates,
)
from .cash_position import (
    CashBalance,
    CashMovement,
    VerifiedCashPosition,
    calculate_verified_cash,
)
from .forecasting import (
    CashFlowCertainty,
    CashForecast,
    ForecastCashFlow,
    ForecastScenario,
    MonteCarloForecast,
    explain_forecast_movement,
    run_cash_forecast,
    run_monte_carlo_forecast,
)
from .normalization import (
    Money,
    NormalizationError,
    extract_invoice_references,
    normalize_counterparty,
    normalize_currency,
    normalize_reference,
    parse_bool,
    validate_currency_and_amount,
)
from .scoring import (
    CandidateFeatures,
    ConfidencePolicy,
    Decision,
    RiskFlag,
    ScoreResult,
    classify_confidence,
    score_candidate,
    score_candidates,
)

__all__ = [
    "Allocation",
    "AllocationCandidate",
    "AllocationSolution",
    "AllocationStatus",
    "GlobalAllocation",
    "GlobalAllocationSolution",
    "GlobalAllocationStatus",
    "CandidateFeatures",
    "CandidatePolicy",
    "CashBalance",
    "CashFlowCertainty",
    "CashForecast",
    "CashMovement",
    "ConfidencePolicy",
    "Decision",
    "ForecastCashFlow",
    "ForecastScenario",
    "InvoiceRecord",
    "MatchCandidate",
    "Money",
    "MonteCarloForecast",
    "NormalizationError",
    "RiskFlag",
    "ScoreResult",
    "TransactionRecord",
    "VerifiedCashPosition",
    "calculate_verified_cash",
    "classify_confidence",
    "explain_forecast_movement",
    "extract_invoice_references",
    "find_candidate_invoices",
    "generate_candidates",
    "normalize_counterparty",
    "normalize_currency",
    "normalize_reference",
    "parse_bool",
    "run_cash_forecast",
    "run_monte_carlo_forecast",
    "score_candidate",
    "score_candidates",
    "solve_global_allocation",
    "solve_payment_allocation",
    "validate_currency_and_amount",
    "verify_allocation",
]
